# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='messages',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\x12\x08messages\"\x17\n\x04\x42\x61se\x12\x0f\n\x07seq_num\x18\x01 \x01(\r\"\'\n\x07PingReq\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0e.messages.Base\"<\n\x07PingRsp\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0e.messages.Base\x12\x13\n\x0breq_seq_num\x18\x02 \x01(\r\"5\n\x04Text\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0e.messages.Base\x12\x0f\n\x07msg_txt\x18\x02 \x01(\tb\x06proto3')
)




_BASE = _descriptor.Descriptor(
  name='Base',
  full_name='messages.Base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='messages.Base.seq_num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='messages.PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='messages.PingReq.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=92,
)


_PINGRSP = _descriptor.Descriptor(
  name='PingRsp',
  full_name='messages.PingRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='messages.PingRsp.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_seq_num', full_name='messages.PingRsp.req_seq_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=154,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='messages.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='messages.Text.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg_txt', full_name='messages.Text.msg_txt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=209,
)

_PINGREQ.fields_by_name['base'].message_type = _BASE
_PINGRSP.fields_by_name['base'].message_type = _BASE
_TEXT.fields_by_name['base'].message_type = _BASE
DESCRIPTOR.message_types_by_name['Base'] = _BASE
DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['PingRsp'] = _PINGRSP
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Base = _reflection.GeneratedProtocolMessageType('Base', (_message.Message,), dict(
  DESCRIPTOR = _BASE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Base)
  ))
_sym_db.RegisterMessage(Base)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQ,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.PingReq)
  ))
_sym_db.RegisterMessage(PingReq)

PingRsp = _reflection.GeneratedProtocolMessageType('PingRsp', (_message.Message,), dict(
  DESCRIPTOR = _PINGRSP,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.PingRsp)
  ))
_sym_db.RegisterMessage(PingRsp)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), dict(
  DESCRIPTOR = _TEXT,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Text)
  ))
_sym_db.RegisterMessage(Text)


# @@protoc_insertion_point(module_scope)
